### ISSUE TITLE
I believe Catalina has broken this

### ISSUE THREAD

**Issue by mendel-lee** [Dalet/140-speedrun-timer#7]
I know that i'm way behind the 8-ball on putting this into my copy of 140 - as a result, attempting to install this has failed. Initial research into the error suggests that this is a MacOS Catalina issue, possibly because Catalina dropped support for 32-bit apps.

The exact error when attempting to run the package reads as thus:

DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
Traceback (most recent call last):
  File "InstallerGUI.py", line 228, in <module>
  File "InstallerGUI.py", line 54, in __init__
  File "InstallerGUI.py", line 185, in find_game
  File "InstallerGUI.py", line 207, in commandLine
  File "subprocess.py", line 856, in __init__
  File "subprocess.py", line 1464, in _execute_child
OSError: [Errno 86] Bad CPU type in executable
[52202] Failed to execute script InstallerGUI

**Comment by Dalet** [comment]
The installer core is compiled in 32 bits indeed.
Can you please try this build?
 https://dalleth.visualstudio.com/_apis/resources/Containers/97343/installer-macOs?itemPath=installer-macOs%2Fspeedrun-timer-installer_9a31bee4b2028c00d32f405b623f16a3e2f995d2_macOS.zip

**Comment by mendel-lee** [comment]
that seems to have worked. Thanks!

**Comment by Dalet** [comment]
New release (v1.1.1) including the fix:
https://github.com/Dalet/140-speedrun-timer/releases/latest
